cleanup: monsterously huge whitespace cleanup, git pre-commit hook.
From this point on, please configure your editor to
  - use spaces instead of tabs
  - warn about (or colorize) whitespace errors (tabs, trailing
    whitespace, emply line with whitespace, etc.)

Also after having clones/pulled this update, please run a
'make install-git-hooks' at the top level directory. This will
install a custom pre-commit hook that prevents subsequent
commits that would accidentially introduce whitespace errors.

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -58,31 +58,35 @@ if [ "$status" != "0" ]; then
 fi
 
 # Check if any TABS have been added to .c or .h files...
+file=""
 git diff --cached $against | \
-    while read line; do
+    while read -r line; do
         case $line in
-            diff\ --git\ a/*)
+            diff\ --git\ a/*)         # 1st diff line, dig out file name
                 file="${line##*b/}"
+                echo "Checking changes to $file..."
                 continue
                 ;;
         esac
         case $file in
-            *.h|*.c) ;;
-            *) continue;;
+            *.h|*.c) ;;               # we process C source code,
+            *) continue;;             # and skip any other files
         esac
-        echo "$line" | grep -q $'\t'
-        if [ "$?" = "0" ]; then
-            echo "WARNING:"
-            echo "WARNING: In $file:"
-            echo "WARNING:"
-            echo "WARNING: Your commit would introduce TABS in a *.c or *.h"
-            echo "WARNING: file and was hence rejected. We prefer not to use"
-            echo "WARNING: TABS in source code to avoid TAB-size dependent"
-            echo "WARNING: incorrect indentation to sneak in. Please fix those"
-            echo "WARNING: errors before trying to commit again."
-            echo "WARNING:"
-            exit 1
-        fi
+        case $line in
+            +*\	*) ;;                 # we flag insertions containing a TAB,
+            *) continue;;             # and skip all other changes
+        esac
+
+        echo "WARNING:"
+        echo "WARNING: In $file: ($line)"
+        echo "WARNING:"
+        echo "WARNING: Your commit would introduce TABS in a *.c or *.h"
+        echo "WARNING: file and was hence rejected. We prefer not to use"
+        echo "WARNING: TABS in source code to avoid TAB-size dependent"
+        echo "WARNING: incorrect indentation to sneak in. Please fix those"
+        echo "WARNING: errors before trying to commit again."
+        echo "WARNING:"
+        exit 1
     done
 
-exit 0
+exit $?
